server:
  port: 9092
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ms-account
          uri: lb://MS-ACCOUNT
          predicates:
            - Path=/account/**
        
        - id: ms-client
          uri: lb://MS-CLIENT
          predicates:
            - Path=/client/**
            
        - id: ms-credit
          uri: lb://MS-CREDIT
          predicates:
            - Path=/credit/**
            
        - id: ms-product
          uri: lb://MS-PRODUCT
          predicates:
            - Path=/product/**
            
        - id: ms-transaction
          uri: lb://MS-TRANSACTION
          predicates:
            - Path=/transaction/transfer/**, /transaction/deposit/**, /transaction/withdrawal/**, /transaction/payment/**
            
        - id: ms-yanki
          uri: lb://MS-YANKI
          predicates:
            - Path=/yanki/**
               
