server:
  port: 8095
spring:
  data:
    mongodb:
      uri: mongodb+srv://BootcampNttdata2024:k9tUuUwOvkdqqrjE@bootcampnttdata2024.zcxsoou.mongodb.net/?retryWrites=true&w=majority
      database: MSDBTRANSACTION
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  
logging:
  level:
    root: INFO
    
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/    

microservices:
  ms-account:
    base-url: http://localhost:9091
  ms-credit:
    base-url: http://localhost:9091
  ms-product:
    base-url: http://localhost:9091
  ms-yanki:
    base-url: http://localhost:9091