server:
  port: 8095
spring:
  data:
    mongodb:
      uri: mongodb+srv://BootcampNttdata2024:k9tUuUwOvkdqqrjE@bootcampnttdata2024.zcxsoou.mongodb.net/?retryWrites=true&w=majority
      database: MSDBTRANSACTION
logging:
  level:
    root: INFO
    
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/    

microservices:
  ms-account:
    base-url: http://localhost:9092
  ms-credit:
    base-url: http://localhost:9092
  ms-product:
    base-url: http://localhost:9092
  ms-yanki:
    base-url: http://localhost:9092